rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  # - rbx-2.0
  - ree
  # - jruby
gemfile:
  - test/gemfiles/Gemfile.rails-3.0.10
  - test/gemfiles/Gemfile.rails-3.1.1
notifications:
  recipients:
    - oleg@twg.ca
branches:
  only:
    - master
  