language: ruby
before_script:
  - rake db:migrate
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
gemfile:
  - test/gemfiles/Gemfile.rails.4.0
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: jruby-19mode
