rvm:
  - 1.8.7
  - 1.9.2
  # - 1.9.3
  - rbx-2.0
  - ree
  # - jruby
gemfile:
  - gemfiles/Gemfile.rails-3.0.x
  - gemfiles/Gemfile.rails-3.1.x
notifications:
  recipients:
    - oleg@twg.ca
branches:
  only:
    - master
  